import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# ──────────────────────────────────────────────
# Page setup
# ──────────────────────────────────────────────
st.set_page_config(
    page_title="Z-Score Outlier Detection",
    layout="centered"
)

st.title("📊 Z-Score Outlier Detection")

st.markdown("""
This app demonstrates **Z-score–based outlier detection**.  
It standardizes each observation and highlights those beyond  
a chosen threshold (e.g. |z| > 3).

**Formula:**  
\\[
z_i = \\frac{x_i - \\mu}{\\sigma}
\\]
""")

# ──────────────────────────────────────────────
# Data input
# ──────────────────────────────────────────────
st.subheader("1️⃣ Upload or enter numeric data")

data_source = st.radio(
    "Choose input method:",
    ["Manual entry", "Upload CSV"],
    horizontal=True
)

if data_source == "Manual entry":
    raw_text = st.text_area(
        "Enter numbers separated by commas:",
        "10, 12, 12, 13, 12, 11, 14, 13, 100"
    )
    try:
        data = np.array([float(x.strip()) for x in raw_text.split(",") if x.strip() != ""])
    except ValueError:
        st.error("Please enter valid numeric values separated by commas.")
        st.stop()
else:
    uploaded = st.file_uploader("Upload a CSV with one numeric column", type=["csv"])
    if uploaded is not None:
        df = pd.read_csv(uploaded)
        st.write(df.head())
        col = st.selectbox("Select numeric column", df.columns)
        data = df[col].values
    else:
        st.info("Please upload a CSV file to continue.")
        st.stop()

# ──────────────────────────────────────────────
# Z-score calculation
# ──────────────────────────────────────────────
st.subheader("2️⃣ Choose threshold and calculate Z-scores")

threshold = st.slider("Z-score threshold for outliers", 1.5, 4.0, 3.0, 0.1)

mean = np.mean(data)
std = np.std(data)
z_scores = (data - mean) / std
outliers = np.abs(z_scores) > threshold

# Results table
results = pd.DataFrame({
    "Value": data,
    "Z-score": np.round(z_scores, 3),
    "Outlier": outliers
})
st.dataframe(results, use_container_width=True)

# ──────────────────────────────────────────────
# Visualization
# ──────────────────────────────────────────────
st.subheader("3️⃣ Visualize results")

fig, ax = plt.subplots(figsize=(8, 4))
ax.scatter(range(len(data)), data, c=~outliers, cmap='coolwarm', s=80, edgecolors='black')
ax.axhline(mean, color='green', linestyle='--', label=f"Mean = {mean:.2f}")
ax.set_xlabel("Observation Index")
ax.set_ylabel("Value")
ax.legend()
st.pyplot(fig)

# ──────────────────────────────────────────────
# Summary
# ──────────────────────────────────────────────
num_outliers = np.sum(outliers)
st.success(f"Detected **{num_outliers}** outlier(s) out of {len(data)} observations.")

if num_outliers > 0:
    st.write("🔎 Outlier values:", data[outliers])
else:
    st.write("✅ No outliers detected under current threshold.")

st.markdown("---")
st.caption("Educational demo • Generated by GPT-5 · © Alastair McBride 2025")
