import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from scipy.stats import norm, skew, kurtosis

# ──────────────────────────────────────────────
# Page setup
# ──────────────────────────────────────────────
st.set_page_config(page_title="Classic Z-Score Analyzer", layout="centered")
st.title("📊 Classic Z-Score Analyzer")

st.markdown("""
Upload a CSV with **one numeric column**.  
This app will:
- Compute **summary statistics** and **Z-scores**  
- Describe the **shape** of the distribution (skewness / kurtosis)  
- Plot the **normal curve** with ±1σ, ±2σ, ±3σ markers  
""")

# ──────────────────────────────────────────────
# File upload
# ──────────────────────────────────────────────
uploaded = st.file_uploader("Upload CSV with one numeric column", type=["csv"])

if uploaded is None:
    st.info("Awaiting CSV upload…")
    st.stop()

df = pd.read_csv(uploaded)
col = st.selectbox("Select numeric column", df.columns)
data = df[col].dropna().astype(float).values

# ──────────────────────────────────────────────
# Summary statistics
# ──────────────────────────────────────────────
n = len(data)
mean = np.mean(data)
std = np.std(data, ddof=1)
minimum = np.min(data)
maximum = np.max(data)
skw = skew(data)
krt = kurtosis(data)

summary = pd.DataFrame({
    "n": [n],
    "Min": [minimum],
    "Max": [maximum],
    "Mean": [mean],
    "Std Dev": [std],
    "Skewness": [skw],
    "Kurtosis": [krt]
}).T.rename(columns={0: "Value"})

st.subheader("📈 Summary Statistics")
st.dataframe(summary, use_container_width=True)

# ──────────────────────────────────────────────
# Distribution description
# ──────────────────────────────────────────────
st.subheader("🧠 Distribution Description")

if abs(skw) < 0.5:
    shape = "approximately **symmetric** (normal-like)"
elif skw > 0.5:
    shape = "**positively skewed** (right-tailed)"
else:
    shape = "**negatively skewed** (left-tailed)"

if abs(krt) < 1:
    peaked = "has a **normal level of peakedness**."
elif krt > 1:
    peaked = "is **leptokurtic** (more peaked with heavier tails)."
else:
    peaked = "is **platykurtic** (flatter with lighter tails)."

st.markdown(f"""
The dataset is {shape} and {peaked}  
- **Mean (μ):** {mean:.3f} **Std Dev (σ):** {std:.3f}  
- **Interpretation:** Most observations lie within ±1σ ≈ {mean-std:.2f} to {mean+std:.2f}.  
""")

# ──────────────────────────────────────────────
# Z-Score calculation
# ──────────────────────────────────────────────
z_scores = (data - mean) / std
z_table = pd.DataFrame({
    "X (Value)": data,
    "Z-Score": np.round(z_scores, 3)
})
st.subheader("📊 Z-Scores Table")
st.dataframe(z_table, use_container_width=True)

# ──────────────────────────────────────────────
# Visualization — Normal Curve with Z-Markers
# ──────────────────────────────────────────────
st.subheader("📈 Normal Distribution Visualization")

x = np.linspace(mean - 4*std, mean + 4*std, 800)
y = norm.pdf(x, mean, std)

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=x, y=y, mode="lines", line=dict(color="blue", width=2),
    name="Normal PDF"
))

# Mean and σ lines
fig.add_trace(go.Scatter(
    x=[mean, mean], y=[0, max(y)],
    mode="lines", line=dict(color="green", dash="dash"),
    name="Mean (μ)"
))
for k in [1, 2, 3]:
    fig.add_trace(go.Scatter(
        x=[mean + k*std, mean + k*std], y=[0, norm.pdf(mean + k*std, mean, std)],
        mode="lines", line=dict(color="gray", dash="dot"), showlegend=False))
    fig.add_trace(go.Scatter(
        x=[mean - k*std, mean - k*std], y=[0, norm.pdf(mean - k*std, mean, std)],
        mode="lines", line=dict(color="gray", dash="dot"), showlegend=False))

# Data points overlay
fig.add_trace(go.Scatter(
    x=data, y=norm.pdf(data, mean, std),
    mode="markers", name="Data Points",
    marker=dict(color="red", size=6, symbol="circle")
))

fig.update_layout(
    title="Normal Distribution — Mean and Standard Deviations",
    xaxis_title="Value (X)",
    yaxis_title="Probability Density",
    template="plotly_white"
)

st.plotly_chart(fig, use_container_width=True)

st.caption("Educational demo • Classic Z-Score method • Generated by GPT-5 · © Alastair McBride 2025")

